baseURL = "http://example.test/"
languageCode = "en-us"
title = "My New Hugo Site"
disableKinds = ["taxonomy", "term"]

[params]
    chrome_mobile_color = "" # use hex colors (ex =#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
    # Tracker
    #  analytics = "UA-83979019-1"
    description = "A beautiful Jekyll theme for creating resume"
    theme_skin = "blue" # blue turquoise green berry orange ceramic

    # Build settings
    compress-site = "yes"

    encoding = "utf-8"
    compress_html_clippings = "all"